### ISSUE TITLE
go-signature-statusbar really slow

### ISSUE THREAD

**Issue by henpa** [wndhydrnt/go-signature-statusbar#17]
Hi, I'm 'kinda' new to Atom and I've just installed go-plus which I believe installed go-signature-statusbar too. But I noticed that Atom became very slow while moving the cursor around, so I tried disabling packages one by one... then I found out that when I disable go-signature-statusbar, editing and cursor moving becomes responsive again.

Is there a reason that this package makes my Atom so slow while editing? Perhaps I'm doing something wrong?  I'm using 1.17.2 on Windows 10.

Thanks

**Comment by nkovacs** [comment]
You're not the only one. I disabled this plugin and blacklisted it in go-plus since I never even used it, it just made Atom unbearably slow.

As for the reason: each time the cursor moves, it immediately tries to figure out what function you're standing on. A debounce would be a trivial optimization.

**Comment by nkovacs** [comment]
This fixes it: https://github.com/wndhydrnt/go-signature-statusbar/compare/master...nkovacs:patch-2

I didn't open a pull request because you should probably use lodash.debounce instead of the homemade solution in there.

**Comment by ericychoi** [comment]
just wanted to +1 on this.. I had to reluctantly disable this extension which I think is tremendously useful.

**Comment by skevy** [comment]
Any chance you could release this fix?

**Comment by skevy** [comment]
@wndhydrnt Thanks!
