### ISSUE TITLE
Utilize Guru instead of GoCode

### ISSUE THREAD

**Issue by otm** [wndhydrnt/go-signature-statusbar#8]
First, I really like the plugin.

Have you looked at Guru instead if GoCode? With Guru I think your code would become a bit easier and you could also get more information.  Please note that I have truncated file paths bellow to make examples easier to read in the issue.

Package: golang.org/x/tools/cmd/guru

Example on function:

```
guru describe main.go:#323
main.go:21.25-21.39: reference to method func (*github.com/gorilla/mux.Route).GetPathTemplate() (string, error)
github.com/gorilla/mux/route.go:549:17: defined here
```

Example on variable (definition):

```
main.go:21.2-21.9: definition of var template string
```

Example on variable (same as above but when used)

```
main.go:25.31-25.38: reference to var template string
main.go:21:2: defined here
```

Example of constant: 

```
main.go:27.42-27.44: reference to const url untyped string of constant value "http://example.com"
main.go:12:7: defined here
```

With this type of information there are two benefits:
1 . Support is extended to show type information on variables and constants, and not just function signature
2. Links can be created for "jump to definition"

**Comment by wndhydrnt** [comment]
Thanks for pointing me to guru, never heard of it before. I played around on the command line and found a few things that currently make it not a good fit for replacing gocode:
- guru returns the full path to structs passed to a function as arguments or returned by a function, like
  `func(n github.com/wndhydrnt/proxym/types.Notifier)`. This requires the string to be reformatted in order to avoid long signatures that are being truncated in the status bar, which [was already an issue](https://github.com/wndhydrnt/go-signature-statusbar/issues/4).
- The output returned by guru does not contain the name of the function. I personally like that it is possible to display the name in the status bar.
- guru appears to be much slower than gocode. Displaying the signature of a function in a moderately large project took ˜2s while gocode needed just about 100ms with a clean cache.

> Links can be created for "jump to definition"

You should give [navigator-godef](https://github.com/joefitzgerald/navigator-godef) a try. I use it a lot to jump to the definition of a function and back.

**Comment by otm** [comment]
Hi

Thanks for looking into it. I'm already using godef allot.

The big thing that I'm missing is type hinting on variables and constants.
